export const theme = {
  colors: {
    primary: '#8B7EC8',
    primaryLight: '#B8A9E3',
    primaryDark: '#6B5BA8',
    primarySoft: '#E8E3F5',
    secondary: '#A78BFA',
    secondaryLight: '#C4B5F0',
    accent: '#C4A5F5',
    accentLight: '#E0D4F8',
    background: '#FFFFFF',
    backgroundLight: '#F8F6FF',
    backgroundSecondary: '#F3F0FF',
    backgroundGradient: ['#F8F6FF', '#FFFFFF'],
    text: '#2D2D2D',
    textLight: '#6B6B6B',
    textMuted: '#9B9B9B',
    border: '#E8E3F5',
    borderLight: '#F0EDF8',
    success: '#A8D5BA',
    warning: '#E8C4A5',
    error: '#E8A5A5',
    white: '#FFFFFF',
    purple50: '#F8F6FF',
    purple100: '#F0EDF8',
    purple200: '#E8E3F5',
    purple300: '#D4C8EB',
    purple400: '#B8A9E3',
    purple500: '#8B7EC8',
    purple600: '#6B5BA8',
  },
  fonts: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 999,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
};
