export const theme = {
  colors: {
    primary: '#9B7EDE',
    primaryLight: '#C4B5E0',
    primaryDark: '#7B5DB8',
    secondary: '#FFB6C1',
    secondaryLight: '#FFD1DC',
    accent: '#B5E5CF',
    accentLight: '#D4F4E6',
    background: '#FFFFFF',
    backgroundLight: '#F5F0FF',
    backgroundSecondary: '#FFF8F0',
    text: '#2D2D2D',
    textLight: '#6B6B6B',
    textMuted: '#9B9B9B',
    border: '#E8E0F5',
    success: '#A8E6CF',
    warning: '#FFD3A5',
    error: '#FFAAA5',
    white: '#FFFFFF',
  },
  fonts: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 999,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
};
